### ISSUE TITLE
Parsing JSON

### ISSUE THREAD

**Issue by nuclearsiloman** [nagaozen/asp-xtreme-evolution#10]
Hi Fabio,
I've used json2.asp for creating JSON strings, but am having issues parsing incoming data.

Here is a sample string:
[
{"Product Line":"B5","Model":"B521432CSSK","length":"14","Column1":"14'x5\" Channel Buggy Hauler","Dealer Cost":"$2,685.00"},
{"Product Line":"B5","Model":"B521632CSSK","length":"16","Column1":"16'x5\" Channel Buggy Hauler","Dealer Cost":"$2,684.00"},
{"Product Line":"B5","Model":"B521832CSSK","length":"18","Column1":"18'x5\" Channel Buggy Hauler","Dealer Cost":"$2,719.00"}
]

When I run the following:
  dim info : set info = JSON.parse(join(array(ProductFeed)))
    for each key in info.keys()
        Response.write key
    next
  set info = nothing

I get numbers.  If I remove the brackets at the beginning/end of the string, I get "Product Line", "Model", etc. - but I only get the first row of the string.

I need to loop through the whole string, get the name and value pair, process, go to the next row....
I appreciate you're a busy man, but if you could provide some guidance it would be very much appreciated.

**Comment by coax** [comment]
`
For each key in JSON.enumerate()
Response.Write JSON.get(key).get("Product Line")
Next
`

**Comment by coax** [comment]
Your JSON data is incorrect, you have an extra " (apostrophe) before ...Channel Buggy... and need to escape that character first.

When you fix that, you can parse it this way:
```
Set info = json.parse(join(array(ProductFeed)))
For each key in info.enumerate()
	Response.Write info.get(key).get("Product Line") & "<br>"
Next
Set info = Nothing
```

**Comment by nuclearsiloman** [comment]
Thanks for the reply!  the ' mark is the 'feet' measurement, which I guess should be escaped.  I've removed it altogether and am still having an issue.

'Enumerate' is not a method in json2.asp so I changed it to keys().  No error, but nothing is being returned.

**Comment by nuclearsiloman** [comment]
Maybe I'm using an older version of json2.asp?  When  using 'enumerate' I get:  
Object doesn't support this property or method: 'enumerate'
Let me get the latest version.

**Comment by nuclearsiloman** [comment]
That was it.  The codebase that uses json2.asp is a bit old.  I replaced it with the latest version and it appears to be cooking with heat now.  Thank you for your help.

**Comment by nuclearsiloman** [comment]
BTW- what would the syntax be to get the data by position.  So instead of:

Response.Write info.get(key).get("Product Line") & "<br>"
something like:
Response.Write info.get(key).get(0) & "<br>" for the first position?  What I'm reading has the key names and number of keynames change.

**Comment by nuclearsiloman** [comment]
Interestingly.... I can get "Model" two ways:
For each key in info.enumerate()
	Response.Write info.get(key).get("Model") & "<br>"
        Response.Write info.get(key).model & "<br>"
    Next

But cannot figure out how to reference that position in the array.

**Comment by coax** [comment]
I don't think you can use it that way.

**Comment by nagaozen** [comment]
```vbs
set info = json.parse(ProductFeed)' ProductFeed should be a json string like [ { ... }, { ... }, ..., { ... } ]
' two ways to iterate javascript arrays:
' i.
for each key in info.enumerate()' also works with javascript objects
	Response.write info.get(key).get("Product Line") & "<br>"
next
set info = nothing
' ii.
for i = 0 to info.length - 1
	Response.write info.get(i).get("Product Line") & "<br>"
next
```

But I'd go this code:

```vbs
with JSON.parse(ProductFeed)
	for each i in .enumerate()
		with .get(i)
			Response.write join( array( _
				.get("Product Line"), _
				.Model, _
				.length, _
				.Column1, _
				.get("Dealer Cost") _
			), "<br/>" )
		end with
	next
end with
```
