### ISSUE TITLE
lack introductions

### ISSUE THREAD

**Issue by greatbody** [nagaozen/asp-xtreme-evolution#6]
you need to make sure that every one knows how to config it!

we need to alter the file:
\instance\config\setting.xml
```xml
<settings>
    <common>
        <name>ASP Xtreme Evolution</name>
        <version>1.4.9.999α</version>
        <environment>DEVELOPMENT</environment>
        <uri>[your web site lurl]</uri>
    </common>
...
```
we need to make sure this uri is right before we start to use it ?

and ,how to create a new view? a new route? and a new controller?

i know how to do it in rails,can you describe it more specifically?

many thanks from China.

**Comment by nagaozen** [comment]
Yes, you need to configure `/instance/config/settings.xml` to your data.

ASP Xtreme Evolution Framework is loose about views, use whatever you like most, mustache, handlebars, xslt, react etc. Just save it at `/app/views/<web|mobile|touch>/<view>`

Take a look at <http://zend.lojcomm.com.br/goodies/asp-xtreme-evolution/>. Its a bit old but will help a lot with your questions.

Best regards,
nagaozen
