### ISSUE TITLE
Markdown Causes "Out of Stack Space" Error when makeHtml is used many times

### ISSUE THREAD

**Issue by robarwebservices** [nagaozen/asp-xtreme-evolution#7]
I use makeHtml in a loop when printing comments which are stored in markdown. 

When I get past about 20 comments e.g. makehtml() is called about 20 times, I get an "out of stack space" error. 

Any thoughts?  I don't want to have to destroy and re-create the whole markdown object for each comment obviously because of the negative performance impact of doing so

For now, I use a counter to count iterations and just terminate and re-initiate the markdown object at every 10 iterations. That works most of the time but sometimes, not. Obviously isn't optimal.

**Comment by nagaozen** [comment]
Could you please post your procedure and the markdown datasource for further testing?

Thanks you,
nagaozen

**Comment by nagaozen** [comment]
Cannot proceed any further without any material to work with. WONT FIX!
