### ISSUE TITLE
Email account settings

### ISSUE THREAD

**Issue by strider72** [nagaozen/asp-xtreme-evolution#8]
I want to send emails from my site, but I don't see how to set the From account settings.  
Username? Password? Server?

I've read this, and I can't find the account info part.  Please help
/lib/axe/docs/files/lib/axe/classes/Utilities/email-asp.html

**Comment by nagaozen** [comment]
That's because those settings are related to the Adapter Layer. You should either use an existing one or implement your own respecting Email_Interface.
